Repository cfug/flutter.cn, pull requests merged in 2020-12, with the labels that each got.

#762 [翻译完成] src/docs/release/breaking-changes/parent-data-widget-generic-type.md
  src/docs/release/breaking-changes/parent-data-widget-generic-type.md
Labels: PRI: 待修改, PRI: 需要校对, Review: ~30分钟

#764 [完成翻译] src/docs/development/add-to-app/android/add-flutter-fragment.md
  src/docs/development/add-to-app/android/add-flutter-fragment.md
Labels: PRI: 需要校对, Review: 30~45分钟

#768 [内容更新] src/docs/get-started/install/windows.md
  src/docs/get-started/install/_get-sdk-win.md
Labels: PRI: 需要校对, Review: ~30分钟, S: 修改 (Fixes), S: 起步 (Get started)

#775 Update SJTUG's description
  src/community/china.md
Labels: PRI: 需要校对, S: Team
