Repository cfug/flutter.cn, pull requests merged in 2021-09, with the labels that each got.

#950 Improve all issue templates
  .github/ISSUE_TEMPLATE/1_page_issue.yml
  .github/ISSUE_TEMPLATE/2_mirror_issue.yml
  .github/ISSUE_TEMPLATE/2_topic_request.yml
  .github/ISSUE_TEMPLATE/3_design_issue.yml
  .github/ISSUE_TEMPLATE/4_infrastructure.yml
  .github/ISSUE_TEMPLATE/mirrors_issue.md
Labels: S: Team

#959 [sync] 2021/09/14
  src/docs/development/tools/sdk/release-notes/release-notes-2.5.0.md
  src/docs/get-started/install/_get-sdk-linux.md
  src/docs/get-started/install/_get-sdk-mac.md
  src/docs/get-started/install/macos.md
  src/jobs/android.html
  src/jobs/index.md
Labels: S: Team

#964 [内容修订] 修正部分 `:` <=> `<br>` 问题
  src/docs/cookbook/testing/widget/introduction.md
  src/docs/deployment/ios.md
  src/docs/development/packages-and-plugins/developing-packages.md
  src/docs/development/tools/vs-code.md
  src/docs/development/ui/animations/implicit-animations.md
  src/docs/development/ui/layout/adaptive-responsive.md
  src/docs/resources/faq.md
Labels: PRI: 需要校对, Review: ~30分钟

#980 [内容修订] 修复部分错误的链接
  src/desktop.md
  src/docs/development/data-and-backend/json.md
  src/docs/development/platform-integration/web.md
  src/docs/development/tools/vs-code.md
  src/docs/development/ui/animations/hero-animations.md
  src/docs/get-started/flutter-for/react-native-devs.md
  src/docs/resources/faq.md
  src/docs/testing/code-debugging.md
  src/docs/testing/debugging.md
Labels: PRI: 需要校对, Review: 30~45分钟, S: Team

#967 [完成翻译] src/dash/index.md
  src/dash/index.md
Labels: PRI: 待润稿, Review: ~30分钟

#984 [内容修订] 修复无效的链接引用
  src/_includes/docs/dart-tool.md
  src/docs/codelabs/index.md
  src/docs/codelabs/layout-basics.md
  src/docs/cookbook/effects/gradient-bubbles.md
  src/docs/cookbook/gestures/handling-taps.md
  src/docs/cookbook/networking/fetch-data.md
  src/docs/deployment/android.md
  src/docs/development/data-and-backend/firebase.md
  src/docs/development/data-and-backend/json.md
  src/docs/development/data-and-backend/state-mgmt/options.md
  src/docs/development/packages-and-plugins/developing-packages.md
  src/docs/development/packages-and-plugins/using-packages.md
  src/docs/development/platform-integration/c-interop.md
  src/docs/development/platform-integration/platform-channels.md
  src/docs/development/platform-integration/web.md
  src/docs/development/tools/devtools/memory.md
  src/docs/development/tools/devtools/overview.md
  src/docs/development/ui/animations/hero-animations.md
  src/docs/development/ui/animations/index.md
  src/docs/development/ui/animations/overview.md
  src/docs/development/ui/assets-and-images.md
  src/docs/development/ui/layout/adaptive-responsive.md
  src/docs/development/ui/layout/index.md
  src/docs/development/ui/layout/responsive.md
  src/docs/development/ui/widgets-intro.md
  src/docs/get-started/flutter-for/android-devs.md
  src/docs/get-started/flutter-for/ios-devs.md
  src/docs/get-started/flutter-for/react-native-devs.md
  src/docs/get-started/flutter-for/xamarin-forms-devs.md
  src/docs/get-started/install/_get-sdk-chromeos.md
  src/docs/get-started/install/_get-sdk-linux.md
  src/docs/get-started/test-drive/_androidstudio.md
  src/docs/get-started/test-drive/_terminal.md
  src/docs/null-safety.md
  src/docs/reference/crash-reporting.md
  src/docs/resources/architectural-overview.md
  src/docs/resources/faq.md
  src/docs/resources/videos.md
  src/docs/testing/code-debugging.md
  src/docs/whats-new.md
Labels: PRI: 需要校对, Review: ~30分钟, S: Team

#986 [内容修订] 修复无效的链接引用 pt.2
  src/docs/development/data-and-backend/firebase.md
  src/docs/development/packages-and-plugins/developing-packages.md
  src/docs/development/platform-integration/web.md
  src/docs/resources/faq.md
Labels: Review: ~30分钟, S: Team

#983 ci: check reference links
  .github/workflows/check.yml
  tool/markdown_check_reference_links.py
Labels: S: Team

#987 [内容修订] 修复已知页面问题
  src/docs/codelabs/dart-cheatsheet.md
  src/docs/deployment/android.md
  src/docs/development/data-and-backend/state-mgmt/ephemeral-vs-app.md
  src/docs/development/data-and-backend/state-mgmt/simple.md
  src/docs/development/packages-and-plugins/developing-packages.md
  src/docs/development/tools/devtools/_profiler.md
Labels: S: Team

#985 [完成翻译] src/docs/development/tools/flutter-fix.md
  src/docs/development/tools/flutter-fix.md
Labels: S: 开发文档 (Development), PRI: 待润稿, Review: ~30分钟
