Repository cfug/flutter.cn, pull requests merged in 2025-04, with the labels that each got.

#1554 [🤖bot] Update: host-redirect.min.js
  src/content/assets/js/host-redirect.min.js
Labels: auto.PR

#1556 [内容修订] src/content/community/china/index.md
  src/content/community/china/index.md
Labels: S: 修改 (Fixes)

#1559 [完成翻译] src/content/get-started/fundamentals/widgets.md
  src/content/get-started/fundamentals/widgets.md
Labels: Status: 校对已认领

#1501 [完成翻译] src/content/cookbook/effects/staggered-menu-animation.md
  src/content/cookbook/effects/staggered-menu-animation.md
Labels: Status: 校对已认领
